### ISSUE TITLE
Similar startup project

### ISSUE THREAD

**Issue by mscharley** [NoNameProvided/typeguard-composer#1]
Hey there,

I just happened to see your release on NPM as I was also doing a release. It looks like we're starting [similar projects](https://github.com/mscharley/generic-type-guard) and I was wondering if perhaps we should work together on this instead.

We seem to have similar goals, but different implementations. I've gone for strict type guards support which means you get a real type guard out the other end which is usually important for my projects, where you've opted for a schema based approach with makes getting a real type guard as a result a bit harder if not impossible but presents a bit cleaner API.

**Comment by NoNameProvided** [comment]
Hey @mscharley! Thanks for reaching out! 

I am afraid I don't understand what do you mean by "real type guard".

As both of the projects are pretty new, I have to say we should still experiment and try to find the best ways to solve our problems, a co-operation at this time would not work well in my opinion, but as always I am open to any discussion about the topic.

**Comment by mscharley** [comment]
By 'real typeguard' I mean something that conforms to the type `<T>(x: any): x is T => true` which lets typescript do the following sorts of things:

```
let foo: any = 10;

if (isNumber(foo)) {
  // No longer unsafe because typescript knows that foo is actually a number not an any.
  foo -= 1;
}
```

[Documentation](https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-guards-and-differentiating-types)

**Comment by mscharley** [comment]
The other thing I like about the way my API is designed is that it is in fact possible to write type safe typeguards:

```
import * as tg from "generic-type-guard";

interface SimpleInterface {
  str: string;
  num: number;
  b: boolean;
}

// This won't compile - missing the b property
const attempt1: tg.PartialTypeGuard<{}, SimpleInterface> =
  new tg.IntersectionOf(
    tg.hasProperty("str", tg.isString),
    tg.hasProperty("num", tg.isNumber),
  ).get();

// this also fails - str is a string not a number
const attempt2: tg.PartialTypeGuard<{}, SimpleInterface> =
  new tg.IntersectionOf(
    tg.hasProperty("str", tg.isNumber),
    tg.hasProperty("num", tg.isNumber),
  ).with(tg.hasProperty("b", tg.isBoolean)).get();
```

This leads to some interesting properties like the ability to guarantee that your type guards are up to date, even if they are for types defined in libraries.
